# Generated by Django 3.0.7 on 2020-07-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='read_time',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True),
        ),
    ]
