# Generated by Django 3.0.7 on 2020-07-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_read_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='read_time',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
